"""change collection_method to postgres enum

Revision ID: 392cfa2fa328
Revises: 0f479bfa9e23
Create Date: 2024-11-27 11:05:53.547119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392cfa2fa328'
down_revision = '0f479bfa9e23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
