"""update default values

Revision ID: 41336445a49c
Revises: 5651479a454f
Create Date: 2024-12-04 19:35:03.816758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41336445a49c'
down_revision = '5651479a454f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
