version: "3.8"
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DATABASE_URL=postgresql+asyncpg://postgres:password@postgres:5432/news_db
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    network_mode: service:selenium-hub
